version: "2.3"

services:
    r-base:
        build:
            context: .
            dockerfile: Dockerfile
            target: r-basics
        image: landeranalytics/r-base
        container_name: r-basic
        tty: true
        stdin_open: true
        runtime: nvidia
    r-tensorflow:
        build:
            context: .
            dockerfile: Dockerfile
            target: r-tensorflow
        image: landeranalytics/r-tensorflow
        container_name: r-tensorflow
        tty: true
        stdin_open: true
        runtime: nvidia
    r-xgboost:
        build:
            context: .
            dockerfile: Dockerfile
            target: r-xgboost
        image: landeranalytics/r-xgboost
        container_name: r-xgboost
        tty: true
        stdin_open: true
        runtime: nvidia
    r-catboost:
        build:
            context: .
            dockerfile: Dockerfile
            target: r-catboost
        image: landeranalytics/r-catboost
        container_name: r-catboost
        tty: true
        stdin_open: true
        runtime: nvidia
    r-tidyverse:
        build:
            context: .
            dockerfile: Dockerfile
            target: r-tidyverse
        image: landeranalytics/r-tidyverse
        container_name: r-tidyverse
        tty: true
        stdin_open: true
        runtime: nvidia
    r-tidymodels:
        build:
            context: .
            dockerfile: Dockerfile
            target: r-tidymodels
        image: landeranalytics/r-tidymodels
        container_name: r-tidymodels
        tty: true
        stdin_open: true
        runtime: nvidia
    r-timeseries:
        build:
            context: .
            dockerfile: Dockerfile
            target: r-timeseries
        image: landeranalytics/r-timeseries
        container_name: r-timeseries
        tty: true
        stdin_open: true
        runtime: nvidia
    r-glmnet:
        build:
            context: .
            dockerfile: Dockerfile
            target: r-glmnet
        image: landeranalytics/r-glmnet
        container_name: r-glmnet
        tty: true
        stdin_open: true
        runtime: nvidia
    r-tidytext:
        build:
            context: .
            dockerfile: Dockerfile
            target: r-tidytext
        image: r-tidytext
        container_name: landeranalytics/r-tidytext
        tty: true
        stdin_open: true
        runtime: nvidia
    r-network:
        build:
            context: .
            dockerfile: Dockerfile
            target: r-network
        image: landeranalytics/r-network
        container_name: r-network
        tty: true
        stdin_open: true
        runtime: nvidia
    r-optim:
        build:
            context: .
            dockerfile: Dockerfile
            target: r-optim
        image: landeranalytics/r-optim
        container_name: r-optim
        tty: true
        stdin_open: true
        runtime: nvidia
    r-extras:
        build:
            context: .
            dockerfile: Dockerfile
            target: r-extras
        image: landeranalytics/r-extras
        container_name: r-extras
        tty: true
        stdin_open: true
        runtime: nvidia
    r-stan:
        build:
            context: .
            dockerfile: Dockerfile
            target: r-stan
        image: landeranalytics/r-stan
        container_name: r-stan
        tty: true
        stdin_open: true
        runtime: nvidia
    rstudio:
        build:
            context: .
            dockerfile: Dockerfile
            target: rstudio
        image: landeranalytics/rstudio
        container_name: rstudio
        tty: true
        stdin_open: true
        runtime: nvidia
        environment:
            - PASSWORD=badpassword
        ports:
            - "8787:8787"
        expose:
            - "8787"
    r-ml:
        build:
            context: .
            dockerfile: Dockerfile
            target: r-ml
        image: landeranalytics/r-ml
        container_name: r-ml
        tty: true
        stdin_open: true
        runtime: nvidia
        ports:
            - "8787:8787"
        environment:
            - PASSWORD=badpassword
